name: Curriculum Solution Branch Splitter

on:
  push:
    branches: curriculum
    paths: index.ipynb

jobs:
  run_branch_splitter:
    uses: learn-co-curriculum/dsc-github-actions-files/.github/workflows/test.yml@a55a8f17c497a0a53505aa862784e0d8482fd414
