name: Curriculum Solution Branch Splitter

on:
  push:
    branches: curriculum
    paths: index.ipynb

jobs:
  Test_remote_action:
    uses: learn-co-curriculum/dsc-github-actions-files/.github/workflows/branch_split.yml@b9a77428ddc1e97d378b3138be19f9e4cec0cdc1
    secrets: inherit
   
