name: Curriculum Solution Branch Splitter

on:
  push:
    branches: curriculum
    paths: index.ipynb

jobs:
  - name: Test remote action
    uses: learn-co-curriculum/dsc-github-actions-files/.github/workflows/test.yml
   
