name: Sync with Canvas

on:
  push:
    branches: [curriculum]
    paths:
      - "index.ipynb"

jobs:
  sync:
    name: Sync with Canvas

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6

      - name: Install github-to-canvas
        run: gem install github-to-canvas
      
      - name: Branch splitter sync
        run: python https://raw.githubusercontent/learn-co-curriculum/dsc-curriculum-guidelines/master-solution-branch-splitter/index.py -m 'syncing changes across branches'

      # Secret stored in learn-co-curriculum Settings/Secrets
      - name: Sync from .canvas file
        run: github-to-canvas -a -lr 
        env:
          CANVAS_API_KEY: ${{ secrets.CANVAS_API_KEY }}
          CANVAS_API_PATH: ${{ secrets.CANVAS_API_PATH }}

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
