name: Sync with Canvas

on:
  push:
    branches: curriculum
    paths: index.ipynb
    
  workflow_dispatch:

jobs:
  build:

    runs-on: macos-latest

    steps:
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8.5
          check-latest: true
          
      - name: Install GitPython
        run: pip install GitPython
        
      - name: Install Jupyter Notebook
        run: pip install notebook
          
      - name: Check git version
        run: git --version

      - name: Install github-to-canvas
        run: gem install github-to-canvas 
        
      - uses: actions/checkout@v3
        with:
          ref: main
      
      - uses: actions/checkout@v3
        with:
          ref: solution
        
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: curriculum
          
      - name: Test path
        run: pwd
      
      - name: Branch splitter sync
        run: python splitter.py  -m 'syncing changes across branches'

      # Secret stored in learn-co-curriculum Settings/Secrets
      - name: Sync from .canvas file
        run: github-to-canvas -a -lr 
        env:
          CANVAS_API_KEY: ${{ secrets.CANVAS_API_KEY }}
          CANVAS_API_PATH: ${{ secrets.CANVAS_API_PATH }}
