name: Branch Splitter

on:
  push:
    branches: curriculum
    paths: index.ipynb
    
  workflow_dispatch:

jobs:
  build:

    runs-on: macos-latest

    steps:
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
            python-version: 3.8
            check-latest: true

      - name: Test path
        run: pwd

      - name: Splitter
        run: python splitter.py -m 'syncing branches'
